name: smart_exchange
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  # location: ^4.3.0
  english_words: ^4.0.0
  provider: ^6.0.0
  image_picker: ^0.8.6
  flutter_launcher_icons: ^0.13.1
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_ui_auth: ^1.11.0
  intl: ^0.18.1
  firebase_database: ^10.3.8
  cloud_firestore: ^4.13.6
  flutter_localizations:
    sdk: flutter
  firebase_ui_localizations: ^1.2.0
  geolocator: ^10.1.0
  firebase_storage: ^11.6.0
  geocoding: ^2.1.1
  flutter_svg: ^2.0.9
  file_picker: ^6.1.1
  firebase_core_web: ^2.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo_square.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/